### ISSUE TITLE
Add Hera stack trace to workflow error message

### ISSUE THREAD

**Issue by JPZ13** [argoproj-labs/hera#676]
**Is your feature request related to a problem? Please describe.**
When running a Hera workflow if there is an error related Python code, it would be helpful to surface the line or lines in which that error was raised in the Python code in the standard error of the pod running that section of the workflow

**Describe the solution you'd like**
Surfacing the line number where the Python error was raised in the standard error of the pod running the logs

**Additional context**
Initially heard this request from Anders and others

**Comment by elliotgunton** [comment]
Hera already surfaces the error line, but it is not accurate for inline scripts because of the required boilerplate. E.g. inline scripts:

```py
from hera.workflows import Workflow, script


@script(constructor="inline")
def divide_by_zero():
    print("This is about to fail")
    x = 1 / 0
    print(x)


with Workflow(
    generate_name="inline-script-error-",
    entrypoint="divide-by-zero",
) as w:
    divide_by_zero()
```

Becomes in the YAML:

```yaml
        source: |-
          import os
          import sys
          sys.path.append(os.getcwd())
          print('This is about to fail')
          x = 1 / 0  # This is line 5
          print(x)
```

Logs:

```
This is about to fail
Traceback (most recent call last):
  File "/argo/staging/script", line 5, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
```

So you can at least search the code line `x = 1 / 0` itself in your code base.


Runner scripts have the the full, accurate line, but it is slightly buried in the stack due to the way Hera runs the user function:

```py
from hera.workflows import Workflow, script


@script(constructor="runner")
def divide_by_zero():
    print("This is about to fail")
    x = 1 / 0  # this is line 7 of the full Python file
    print(x)


with Workflow(
    generate_name="runner-script-error-",
    entrypoint="divide-by-zero",
) as w:
    divide_by_zero()
```

Logs:

```
time="2025-07-29T10:01:29 UTC" level=info msg="capturing logs" argo=true
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.13/site-packages/hera/workflows/runner.py", line 6, in <module>
    _run()
    ~~~~^^
  File "/usr/local/lib/python3.13/site-packages/hera/workflows/_runner/util.py", line 297, in _run
    result = _runner(args.entrypoint, template_inputs)
  File "/usr/local/lib/python3.13/site-packages/hera/workflows/_runner/util.py", line 271, in _runner
    return function(**function_kwargs)
  File "/usr/local/lib/python3.13/site-packages/hera/workflows/_runner/util.py", line 73, in inner
    return f(**filtered_kwargs)
  File "/usr/local/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 39, in wrapper_function
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 136, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/app/hera_scratch/workflow.py", line 7, in divide_by_zero
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
This is about to fail
time="2025-07-29T10:01:30 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

It's important to keep the full stack trace in case there is a problem with the runner code itself. Though we could see if we can only show the user-code portion of the stack trace by adding the debug mode #972 which can turn on the full stack trace (but can be off by default).
