### ISSUE TITLE
hera.exceptions.InternalServerError: Server returned status code 500 with message: `template 'steps' type is unknown`

### ISSUE THREAD

**Issue by frank-bee** [argoproj-labs/hera#692]
<h2>Pre-bug-report checklist</h2>

**2. This bug occurs when...**
- running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
If I use the `create_as_workflow()` on a WorkflowTemplate , I get the error below.

_Error log if applicable_:
```
Traceback (most recent call last):
  File "/workspaces/hera-blueprint-example/./src/example_workflow.py", line 9, in <module>
    example_workflow_template.getWorkflowTemplate().create_as_workflow()
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/hera/workflows/workflow_template.py", line 174, in create_as_workflow
    return workflow.create(wait=wait, poll_interval=poll_interval)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/hera/workflows/workflow.py", line 383, in create
    wf = self.workflows_service.create_workflow(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/hera/workflows/service.py", line 889, in create_workflow
    raise exception_from_server_response(resp)
hera.exceptions.InternalServerError: Server returned status code 500 with message: `template 'steps' type is unknown`
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py

@script(
    image=image,
    image_pull_policy=ImagePullPolicy.always
)
def foo():
    from art import art
    from samplemodule import do_something

    # from own code
    do_something()

    # test external package
    art_1 = art("foo")
    print(art_1)

def getWorkflowTemplate():
    with WorkflowTemplate(
        name=name,
        namespace="playground",
        entrypoint="steps",
        service_account_name="argo-workflow"
    ) as w:
        with Steps(name="steps"):
            foo()

    return w


....

example_workflow_template.getWorkflowTemplate().create_as_workflow()

```

**Environment**
 - Version of Hera: 5.5.0
 - Version of Argo: 3.4.3

**Comment by elliotgunton** [comment]
Thank you for the report @frank-bee! Can confirm this is coming from the conversion code [here](https://github.com/argoproj-labs/hera/blob/94b5b2988ea2211b7e9774e2cefbde63b0c14f38/src/hera/workflows/workflow_template.py#LL143C6-L143C43) which doesn't seem to be doing a deep copy, so it loses the steps or tasks of Steps or DAG templates.

**Comment by elliotgunton** [comment]
Fix is now released at https://pypi.org/project/hera/5.5.1/ 🚀 Thank you again for the quick and clear report @frank-bee!

**Comment by frank-bee** [comment]
@elliotgunton  works :-) 
( see here https://github.com/aiknow-public/hera-blueprint )
