### ISSUE TITLE
Empty input in Script runner fails Pydantic validation

### ISSUE THREAD

**Issue by mshatkhin23** [argoproj-labs/hera#694]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [Sort of] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When using the Script runner feature, passing an empty string as an input argument fails at runtime. I believe this has something to do with how the inputs are passed through the source field [here](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/script.py#L428), or how argo itself evaluates the `{{inputs.parameters}}` expression when parameters are empty.  The same issue does not occur when using the inline script constructor.

_Error log if applicable_:
```
W
Traceback (most recent call last):
  File "/opt/bb/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/bb/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 127, in <module>
    _run()
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 120, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 105, in _runner
    return function(**kwargs)
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 27, in inner
    return f(**filtered_kwargs)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 130, in pydantic.decorator.ValidatedFunction.init_model_instance
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Echo
message
  field required (type=value_error.missing)
time="2023-06-24T19:42:03 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

**To Reproduce**

Runner constructor fails.  Replacing runner with inline works.
```py
from hera.workflows import Workflow, Script, script, Steps
from hera.shared import global_config

global_config.set_class_defaults(Script, constructor="runner")
global_config.experimental_features["script_runner"] = True

@script(constructor="runner")
def echo(message: str) -> None:
    print(message)

with Workflow(
        name="hera-playground",
        entrypoint="steps",
    ) as w:
        with Steps(name="steps"):
            echo(arguments={"message": ""})
        return w
```

**Expected behavior**
I expect the Workflow to not fail and accept the empty string as input.

**Environment**
 - OS: iOS
 - Browser: chrome
 - Version of Hera: 5.5.0
 - Version of Argo: 3.4.8

**Additional context**

**Comment by mshatkhin23** [comment]
@samj1912 @elliotgunton

**Comment by samj1912** [comment]
@mshatkhin script runner only supports keyword args. You will need to either set a default value for message in the function or use `*` before message to indicate that it's a kwarg.

**Comment by mshatkhin23** [comment]
This is solved by: https://github.com/argoproj-labs/hera/commit/0c7d0504bfc10ce87bb45a6d0c684e559bca0675

Thanks @samj1912 !

**Comment by mshatkhin23** [comment]
This is solved by: https://github.com/argoproj-labs/hera/commit/0c7d0504bfc10ce87bb45a6d0c684e559bca0675

Thanks @samj1912 !
