### ISSUE TITLE
Output parameter not working as a last step using annotations

### ISSUE THREAD

**Issue by cjxnn** [argoproj-labs/hera#840]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

_Error log if applicable_:
```
Traceback (most recent call last):
  File "/opt/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hera/outputs/parameters'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 313, in <module>
    _run()
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 306, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 277, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 211, in _save_annotated_return_outputs
    _write_to_path(path, output_value)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 231, in _write_to_path
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hera/outputs/parameters'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 313, in <module>
    _run()
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 306, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 277, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 211, in _save_annotated_return_outputs
    _write_to_path(path, output_value)
  File "/layers/com.ds.pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 231, in _write_to_path
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/opt/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/hera/outputs'
time="2023-11-06T10:29:31 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
time="2023-11-06T10:29:31 UTC" level=error msg="cannot save parameter /tmp/hera/outputs/parameters/results" argo=true error="open /tmp/hera/outputs/parameters/results: no such file or directory"
Error: exit status 1
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Workflow

@script()
def stress_test(
...
) -> Annotated[Dict, Parameter(name="results")]:
    return result

with Workflow(name="my-workflow") as w:
    stress_test()
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

**Environment**
 - Browser: [e.g. chrome, safari]
 - Version of Hera: [5.9.0]
 - Version of Argo: [e.g. 3.4.7]

**Additional context**

**Comment by elliotgunton** [comment]
Closing for #841
