### ISSUE TITLE
Script annotations + runner for annotated strings breaks for json strs

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#855]
Discussed with @samj1912 - the runner currently does some implicit json loading of inputs that we'd like to review/remove some of and move the control of loading parameters (e.g. given a json str or yaml str, choose whether to load it via `json.loads` or `yaml.safe_load`). Marked the PR as draft, and will make the change in another PR on top of this one.

Also, this code doesn't deal well with `Annotated` strings, resulting in different behaviour for `my_str: str` and `my_str: Annotated[str, Parameter(...)]` in script parameters https://github.com/argoproj-labs/hera/blob/04eca946cd3ff83beeca536c50c40db8d23ff193/src/hera/workflows/runner.py#L77

_Originally posted by @elliotgunton in https://github.com/argoproj-labs/hera/issues/850#issuecomment-1803751319_

**Comment by elliotgunton** [comment]
We can show the problem with this workflow. The `CustomScriptConstructor` just wraps the runner script constructor to print the incoming kwargs list for sanity checks (i.e. it _does_ receive a json str)

```py
import json
from typing import Annotated

from hera.workflows import Parameter, Steps, WorkflowTemplate, script
from testrunnerloading.custom_runner import CustomScriptConstructor

@script(constructor=CustomScriptConstructor())
def take_json_str(my_json: Annotated[str, Parameter(name="my-json")]):
    """Take a json string, load it and print it."""
    print(json.loads(my_json))


def get_workflow_template() -> WorkflowTemplate:
    """Create and return the test-runner-loading WorkflowTemplate."""
with WorkflowTemplate(
    name="mlplatform.test-runner-loading",
    entrypoint="steps",
) as wt:
    with Steps(name="steps"):
        take_json_str(arguments={"my_json": json.dumps({"key": "value"})})
```

Which gets an error like:

```console
source contents: [{"name":"my_json","value":"{\"key\": \"value\"}"}]
kwargs_list: [{'name': 'my_json', 'value': '{"key": "value"}'}]
calling function
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/testrunnerloading/custom_runner.py", line 350, in <module>
    _run()
  File "/workspace/testrunnerloading/custom_runner.py", line 343, in _run
    result = _runner(args.entrypoint, kwargs_list)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/testrunnerloading/custom_runner.py", line 315, in _runner
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/testrunnerloading/custom_runner.py", line 58, in inner
    return f(**filtered_kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 130, in pydantic.decorator.ValidatedFunction.init_model_instance
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TakeJsonStr
my_json
  str type expected (type=type_error.str)
time="2023-11-09T11:53:38 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```
