### ISSUE TITLE
parameter output regression

### ISSUE THREAD

**Issue by cjxnn** [argoproj-labs/hera#882]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [ ] exporting to YAML
- [ ] submitting to Argo
- [x] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_
cannot output a parameter
_Error log if applicable_:
```
W
Traceback (most recent call last):
  File "/opt//lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt//lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 321, in <module>
    _run()
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 314, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 285, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 36, in inner
    filtered_kwargs = {key: _parse(value, key, f) for key, value in kwargs.items() if _is_kwarg_of(key, f)}
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 36, in <dictcomp>
    filtered_kwargs = {key: _parse(value, key, f) for key, value in kwargs.items() if _is_kwarg_of(key, f)}
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 67, in _parse
    if _is_str_kwarg_of(key, f) or _is_artifact_loaded(key, f) or _is_output_kwarg(key, f):
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 88, in _is_str_kwarg_of
    return issubclass(get_args(type_)[0], str)
TypeError: issubclass() arg 1 must be a class
time="2023-11-28T17:10:39 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
time="2023-11-28T17:10:39 UTC" level=error msg="cannot save parameter /tmp/hera-outputs/parameters/test" argo=true error="open /tmp/hera-outputs/parameters/test: no such file or directory"
Error: exit status 1

```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
@script()
def select() -> Annotated[bool, Parameter(name="test")]:
    """Prepare input requests."""
    return False
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

**Environment**
- Hera Version: 5.10.1
- Python Version: 3.9.0
- Argo Version: 3.X.X

**Additional context**

**Comment by elliotgunton** [comment]
The given script code works fine:

```py
@script()
def test_bool_output() -> Annotated[bool, Parameter(name="an-output")]:
    return False
```

The stack trace for the error is actually from the inputs:

```
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 67, in _parse
    if _is_str_kwarg_of(key, f) or _is_artifact_loaded(key, f) or _is_output_kwarg(key, f):
  File "/layers/com..ds..pip/requirements/lib/python3.9/site-packages/hera/workflows/runner.py", line 88, in _is_str_kwarg_of
    return issubclass(get_args(type_)[0], str)
TypeError: issubclass() arg 1 must be a class
```

But I couldn't reproduce with various combinations of extra kwarg inputs, no inputs, untyped inputs etc, not sure how you're passing values to the script to get this problem.

**Comment by BrandonLiang** [comment]
@cjxnn Hi I am running into a very similar issue, how did you eventually tackle this?
